services:
  backend:
    env_file:
      - ".env"
    image: node:latest
    command: bash -c "npm run dev"
    working_dir: /home/node/app
    ports:
      - 127.0.0.1:8355:8355
    volumes:
      - .:/home/node/app
  
  database:
    env_file: ".env"
    image: postgres:latest
    container_name: postgres_mediq
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./dataset/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  auth_database:
    image: eqalpha/keydb:latest
    container_name: keydb
    expose:
      - 6379
    ports:
      - 6379:6379